//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{
    public partial class CambiarContrasenaPendiente
    {
        protected global::System.Web.UI.WebControls.Panel PnlCuenta;
        protected global::System.Web.UI.WebControls.Label LblCuenta;
        protected global::System.Web.UI.WebControls.Label LblNuevaContrasena;
        protected global::System.Web.UI.WebControls.TextBox TxtNuevaContrasena;
        protected global::System.Web.UI.WebControls.Label LblConfirmacionContrasena;
        protected global::System.Web.UI.WebControls.TextBox TxtConfirmacionContrasena;
        protected global::System.Web.UI.WebControls.Button BtnGuardar;
    }
}
