//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{
    public partial class Ingresar
    {
        protected global::System.Web.UI.WebControls.Label LblUsuario;
        protected global::System.Web.UI.WebControls.TextBox TxtUsuario;
        protected global::System.Web.UI.WebControls.Label LblContrasena;
        protected global::System.Web.UI.WebControls.TextBox TxtContrasena;
        protected global::System.Web.UI.WebControls.Button BtnIngresar;
        protected global::System.Web.UI.WebControls.Button BtnRegistrarme;
        protected global::System.Web.UI.WebControls.Button BtnRecuperarContrasena;
    }
}
