//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{
    public partial class PanelPrincipal
    {
        protected global::System.Web.UI.WebControls.Button BtnPacientes;
        protected global::System.Web.UI.WebControls.LinkButton LnkAltaPaciente;
        protected global::System.Web.UI.WebControls.LinkButton LnkListaPacientes;
        protected global::System.Web.UI.WebControls.Button BtnMedicos;
        protected global::System.Web.UI.WebControls.LinkButton LnkAltaMedico;
        protected global::System.Web.UI.WebControls.HyperLink LnkListaMedicos;
        protected global::System.Web.UI.WebControls.Button BtnEspecialidades;
        protected global::System.Web.UI.WebControls.LinkButton LnkAltaEspecialidad;
        protected global::System.Web.UI.WebControls.LinkButton LnkListaEspecialidades;
        protected global::System.Web.UI.WebControls.Button BtnUsuarios;
        protected global::System.Web.UI.WebControls.LinkButton LnkAltaUsuario;
        protected global::System.Web.UI.WebControls.LinkButton LnkListaUsuarios;
        protected global::System.Web.UI.WebControls.Button BtnTurnos;
        protected global::System.Web.UI.WebControls.LinkButton LnkConfiguracionTurnos;
        protected global::System.Web.UI.WebControls.LinkButton LnkAltaTurno;
        protected global::System.Web.UI.WebControls.LinkButton LnkMisTurnos;
    }
}
