//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{


    public partial class ConfiguracionTurnos
    {
        protected global::System.Web.UI.WebControls.HiddenField HfIdConfiguracionTurno;

        protected global::System.Web.UI.WebControls.Label LblDuracionMinutos;

        protected global::System.Web.UI.WebControls.TextBox TxtDuracionMinutos;

        protected global::System.Web.UI.WebControls.Button BtnGuardar;

        protected global::System.Web.UI.WebControls.Button BtnCancelar;
    }
}
