//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{
    public partial class ListaTurnos
    {
        protected global::System.Web.UI.WebControls.TextBox txtFiltro;

        protected global::System.Web.UI.WebControls.TextBox txtFecha;

        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        protected global::System.Web.UI.WebControls.Button btnBuscar;

        protected global::System.Web.UI.WebControls.Button btnLimpiar;

        protected global::System.Web.UI.WebControls.GridView dgvTurnos;
    }
}
