//------------------------------------------------------------------------------
// <auto-generated>
//     Este codigo fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurnosClinica.Web
{
    public partial class ListaPacientes
    {
        protected global::System.Web.UI.WebControls.Button BtnAltaPaciente;
    }
}
